from .character_prompts import CHARACTER_RESPONSE_PROMPT, CHARACTER_THOUGHT_PROMPT
from .narrator_prompts import NARRATOR_OBSERVATION_PROMPT
from .orchestrator_prompts import ORCHESTRATOR_FLOW_PROMPT
from .play_manager_prompts import SCENARIO_GENERATION_PROMPT, CHARACTER_GENERATION_PROMPT

__all__ = [
    'CHARACTER_RESPONSE_PROMPT',
    'CHARACTER_THOUGHT_PROMPT',
    'NARRATOR_OBSERVATION_PROMPT',
    'ORCHESTRATOR_FLOW_PROMPT',
    'SCENARIO_GENERATION_PROMPT',
    'CHARACTER_GENERATION_PROMPT'
] 